name: React app deployement

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
    
env:
  CI: false

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
